#!/bin/bash
set -e

if [ -z "$1" ]; then
    # Remove windows platform because of
    # https://github.com/mailgun/log/issues/10
    OS_PLATFORM_ARG=(-os="darwin linux")
else
    OS_PLATFORM_ARG=($1)
fi

if [ -z "$2" ]; then
    OS_ARCH_ARG=(-arch="386 amd64 arm")
else
    OS_ARCH_ARG=($2)
fi

# Get rid of existing binaries
rm -f dist/traefik*

# Build binaries
godep go build

